repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: https://github.com/crate-ci/typos
    rev: v1.36.2
    hooks:
      - id: typos

  - repo: <https://github.com/astral-sh/ruff-pre-commit>
    rev: v0.14.4
    hooks:
      - id: ruff-format
        name: 'ğŸ python Â· Format with Ruff'
      # STRICT
      - id: ruff
        args: [--fix]

  # STRICT
  - repo: <https://github.com/RobertCraigie/pyright-python>
    rev: v1.1.407
    hooks:
      - id: pyright
        name: 'ğŸ python Â· Check types'
